secrets:
  pihole-webpassword:
    file: ${HOME}/docker/secrets/pihole_webpassword

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole-pi
    secrets:
      - pihole-webpassword
    environment:
      TZ: America/New_York
      PIHOLE_UID: 115
      PIHOLE_GID: 124
      WEBPASSWORD_FILE: /run/secrets/pihole-webpassword
      FTLCONF_dns_upstreams: 9.9.9.9;149.112.112.112
      FTLCONF_dns_listeningMode: local
      FTLCONF_webserver_port: 8000
      FTLCONF_misc_etc_dnsmasq_d: true
    volumes:
      - ${HOME}/docker/etc-pihole:/etc/pihole
      - ${HOME}/docker/etc-dnsmasq.d:/etc/dnsmasq.d
    network_mode: host
    restart: unless-stopped
