name: Automatic Versioning

on:
  push:
    branches:
      - main

jobs:
  make-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v2

      - name: Extract Latest Version from Changelog
        id: extract_version
        run: |
          VERSION=$(grep -oP '## \[\K[0-9]+\.[0-9]+\.[0-9]+' changelog.md | head -n 1)
          echo "Latest version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if Release Already Exists
        id: check_release
        run: |
          # List all releases and check if the version already exists
          RELEASE_EXISTS=$(gh release list --repo $GITHUB_REPOSITORY | grep -w "${{ env.VERSION }}")
          if [ -n "$RELEASE_EXISTS" ]; then
            echo "Release ${{ env.VERSION }} already exists. Update the changelog."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        run: |
          # Create a release with the extracted version number
          gh release create ${{ env.VERSION }} --title "Release ${{ env.VERSION }}" --notes "Release notes for version ${{ env.VERSION }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
